services:
  database:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DB_USER: postgres
      DB_HOST: database
      DB_NAME: task_manager
      DB_PASSWORD: postgres
      DB_PORT: 5432

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: